#!/bin/bash
if [ $# -lt 1 ]; then
	echo "Usage: convert ptc_source_file [output_location]"
	exit
elif [ $# -ge 3 ]; then
	echo "Too many arguments!"
	echo "Usage: convert ptc_source_file [output_location]"
	exit
fi

./resources/tools/txt_to_ptc.py $1
# https://stackoverflow.com/questions/125281/how-do-i-remove-the-file-suffix-and-path-portion-from-a-path-string-in-bash
nosuffix=${1%.*}
nopath=${nosuffix##*/}
mv ${nopath}.PTC ${2:-programs/}
