#!/bin/bash
# usage: nds_extract <ptc_file_name>.nds

NDS_FILE=$1
# ndstool extraction path
EXTRACT_PATH="extract/"
# sdatxtract extraction path
TEMP_PATH="${1%.nds}"

echo "Found .nds file: $NDS_FILE"

echo "Creating directories..."
mkdir "ui/"
mkdir "graphics/"
mkdir "sounds/"

echo "Extracting graphics resources..."
./tools/ndstool -x -d "$EXTRACT_PATH" "$NDS_FILE"
echo "Extracting sound resources..."
./tools/sdatxtract "$NDS_FILE"

echo "Moving graphics resources..."
mv "$EXTRACT_PATH/"*.NSCR "ui/"
mv "$EXTRACT_PATH/"*.NCGR "ui/"
mv "$EXTRACT_PATH/"*.NCLR "ui/"

echo "Moving sample programs..."
for i in "$EXTRACT_PATH"*.PRG
do
	python3 tools/txt_to_ptc.py $i
done
mv *.PTC "../programs/"

echo "Extracting NCGR to .PTC"
python3 tools/ncgr_to_ptc.py "ui/BGU.NCGR" "BGU"
python3 tools/ncgr_to_ptc.py "ui/BGD.NCGR" "BGD"
python3 tools/ncgr_to_ptc.py "ui/BGF.NCGR" "BGF"
python3 tools/ncgr_to_ptc.py "ui/partsSPU.NCGR" "SPU"
python3 tools/ncgr_to_ptc.py "ui/partsSPS.NCGR" "SPS"
python3 tools/ncgr_to_ptc.py "ui/partsSPDK.NCGR" "SPD"

echo "Extracting NCLR to .PTC"
python3 tools/nclr_to_ptc.py "ui/defBGSP.NCLR" "COL0"
python3 tools/nclr_to_ptc.py "ui/defBGSP.NCLR" "COL1"
python3 tools/nclr_to_ptc.py "ui/GRP.NCLR" "COL2"

echo "Moving extracted PTC..."
mv BGU*.PTC "graphics/"
mv BGD*.PTC "graphics/"
mv BGF*.PTC "graphics/"
mv SPU*.PTC "graphics/"
mv SPS*.PTC "graphics/"
mv SPD*.PTC "graphics/"
mv COL*.PTC "graphics/"

echo "Moving sound resources..."
mv "$TEMP_PATH/0/bank/"*.sbnk"" "sounds/"
mv "$TEMP_PATH/0/sequence/"*.sseq"" "sounds/"
mv "$TEMP_PATH/0/wave/"*.swar"" "sounds/"

echo "Removing extraction directories"
rm -r "$TEMP_PATH"
rm -r "$EXTRACT_PATH"
